### ISSUE TITLE
fn return type position

### ISSUE THREAD

**Issue by sp0** [sp0/rust-style#13]
On function signatures, the return type can often be placed in strange positions:
```
pub fn current_mut<'a>(&self,
                       line: &'a mut UnwrappedLine) -> &'a mut FormatToken {
    &mut line.tokens[self.next_token_index]
}
```
This may be a better style:
```
pub fn current_mut<'a>(&self,
                       line: &'a mut UnwrappedLine) 
                       -> &'a mut FormatToken {
    &mut line.tokens[self.next_token_index]
}
```
However, if all the arguments fit on the first line, but the return type doesn't it could end up like this, which is may or may not be desirable:
```
pub fn current_mut<'a>(&self, line: &'a mut UnwrappedLine) 
                       -> &'a mut FormatToken {
    &mut line.tokens[self.next_token_index]
}
```

**Comment by sp0** [comment]
I looked into this particular case. I thought it was strange that it was breaking in paramaters, instead of before the ->, since the the arrow should have a lower split penalty due to not being surrounded by parentheses. Turns out the calculated split penalty of -> is higher than it should be due to bugs in AnnotatingParser. 

The -> token is incorrectly being considered to be a part of the type 'Context', that is being started at the -> token itself. The previous parens context is also not being popped correctly, due to another bug. As we knew already, the AnnotatingParser needs rewritten, probably as some sort of recursive decsent parser, instead of managing a context stack manually.

**Comment by sp0** [comment]
After the above bug was fixed, the output has changed. It currently just indents to a regular continuation indentation.
```
  pub fn add_token_to_state(&self, line: &mut UnwrappedLine, state: &mut LineState,
                              newline: bool, dry_run: bool, whitespace: &mut WhitespaceManager)
        -> Penalty {
```

**Comment by madmalik** [comment]
That looks bad too.

I would look best if a.) the return type would be on the same indentation level and b.) every argument would go on its won line: 

```
    pub fn add_token_to_state(&self, 
                              line: &mut UnwrappedLine, 
                              state: &mut LineState,
                              newline: bool, 
                              dry_run: bool, 
                              whitespace: &mut WhitespaceManager)
                              -> Penalty {
        ...
    }   
```
or even
```
    pub fn add_token_to_state(&self, 
                              line:       &mut UnwrappedLine, 
                              state:      &mut LineState,
                              newline:    bool, 
                              dry_run:    bool, 
                              whitespace: &mut WhitespaceManager)
                              -> Penalty {
        ...
    }   
```

when alignment is allowed.
